# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{thinner}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jeff Larson"]
  s.date = %q{2011-02-01}
  s.default_executable = %q{thinner}
  s.description = %q{Thinner takes a list of urls or newline seperated stdin and purges them from Varnish.}
  s.email = %q{thejefflarson@gmail.com}
  s.executables = ["thinner"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "bin/thinner",
     "doc/Thinner.html",
     "doc/Thinner/Client.html",
     "doc/Thinner/CommandLine.html",
     "doc/Thinner/Configuration.html",
     "doc/Thinner/Purger.html",
     "doc/_index.html",
     "doc/class_list.html",
     "doc/css/common.css",
     "doc/css/full_list.css",
     "doc/css/style.css",
     "doc/file.README.html",
     "doc/file_list.html",
     "doc/frames.html",
     "doc/index.html",
     "doc/js/app.js",
     "doc/js/full_list.js",
     "doc/js/jquery.js",
     "doc/method_list.html",
     "doc/top-level-namespace.html",
     "documentation/css/dawn.css",
     "documentation/css/styles.css",
     "documentation/examples/configure.rb",
     "documentation/examples/purge.rb",
     "documentation/images/proplogo.png",
     "documentation/index.html.erb",
     "index.html",
     "lib/thinner.rb",
     "lib/thinner/client.rb",
     "lib/thinner/command_line.rb",
     "lib/thinner/configuration.rb",
     "lib/thinner/purger.rb",
     "test/helper.rb",
     "test/test_thinner.rb",
     "thinner.gemspec"
  ]
  s.homepage = %q{http://github.com/propublica/thinner}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Thinner removes Varnish cache, as slowly as you need it to.}
  s.test_files = [
    "test/helper.rb",
     "test/test_thinner.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<klarlack>, ["~> 0.0.6"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
    else
      s.add_dependency(%q<klarlack>, ["~> 0.0.6"])
      s.add_dependency(%q<shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<klarlack>, ["~> 0.0.6"])
    s.add_dependency(%q<shoulda>, [">= 0"])
  end
end

